export const DEPARTMENTS = [
  'Medical Devices',
  'Industry X',
  'Industrial & Consumer Products',
  'Software',
  'Testing',
  'Sustainability',
  'Professional Training & Development',
  'Innovation',
  'BFSI',
  'Administration',
  'IT department',
  'Strategy',
  'Board',
  'Production Department',
  'New Product Development',
  'Digital Transformation',
  'Healthcare',
  'Building Information Modeling',
  'Process Industries',
  'Engineering Department Hus',
  'Energy Utilities',
  'Structural Engineering',
  'Purchase Deparment',
  'Sales Department',
  'Marketing Department',
  'Human Resource Department',
  'Finance Department',
  'Electronics Department',
] as const;
