export const DEPARTMENTS = [
  'Administration',
  'BFSI',
  'Board',
  'Building Information Modeling',
  'Digital Transformation',
  'Electronics Department',
  'Energy Utilities',
  'Engineering Department Hus',
  'Finance Department',
  'Healthcare',
  'Human Resource Department',
  'Industrial & Consumer Products',
  'Industry X',
  'Innovation',
  'IT department',
  'Marketing Department',
  'Medical Devices',
  'New Product Development',
  'Process Industries',
  'Professional Training & Development',
  'Production Department',
  'Purchase Deparment',
  'Sales Department',
  'Software',
  'Strategy',
  'Structural Engineering',
  'Sustainability',
  'Testing',
] as const;
